version: '3.3'
services:
  elasticsearch:
    image : docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9092:9200
    networks:
      - elastic
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9092
    ports:
      - 9093:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  elasticsearch-data-volume:
    driver: local

networks:
  elastic:
    driver: bridge