version: "3.3"
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8000:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=majoo
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.130.233.190:19092,10.130.233.190:29092,10.130.233.190:39092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=10.130.233.190:22181,10.130.233.190:32181,10.130.233.190:42181
      - KAFKA_CLUSTERS_0_KSQLDBSERVER=10.130.233.190:8088
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=10.130.233.190:8081
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=kafka-connect
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=10.130.233.190:8083
